name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install wheel
        pip install pylint-json2html
    - name: Analysing the code with pylint
      run: |
        pylint sec-certs --output-format=json > lint/log.json
        pylint-json2html lint/log.json -o log.html
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: lint-artifact
        path: lint/log.html
        
